### ISSUE TITLE
get_obj_or_404 is shit

### ISSUE THREAD

**Issue by VMCvastry** [DannyAntonelli/Let-Me-Code#1]
The way is implemented now if any of the objects in a request fails you get "not found" without any info on which request failed

**Comment by DannyAntonelli** [comment]
I changed the share project API, so that every method uses at most one `get_object_or_404`. Every method that uses it is in relation with a particular User/Project/File so that the frontend knows that the "_not found_" is related to the single resource being requested.

Commit: 96dc4a77f0868aa12342303120a055913f297ac8
